### PR TITLE
Added Request variable to the Resource query's

### LINKED ISSUE #47: feat: Give resource queries access to request

### PR DESCRIPTION
**Pull request by DanielvdSpoel**

### CODE REVIEW

**Comment by DanielvdSpoel** [comment]
This is a fix for issue #47

**Comment by Larsklopstra** [comment]
@DanielvdSpoel could you type hint the request?

**Comment by Larsklopstra** [comment]
closes #47

**Comment by DanielvdSpoel** [comment]
What do you mean by that? I allready added it in the code blocks above the functions?

**Comment by Larsklopstra** [comment]
@DanielvdSpoel I prefer types rather than docs, I'm planning to remove most of them where applicable

**Pull request closed without merging**
